name: Build and Commit Resume

on:
  push:
    paths:
      - "BilalShehzadResume.md"   # Only trigger on changes to resume.md

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run in Docker container
      uses: docker://ghcr.io/bilalqtech/markdown-resume:latest
      with:
        entrypoint: /bin/bash
        args: |
          -c "
          # Build resume
          make clean
          make all
          
          # Commit and push resume files
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add *.pdf *.docx *.txt *.html
          git commit -m 'Auto-update resume formats [skip ci]' || echo 'No changes to commit'
          git push origin HEAD
          "

    # Optional: Upload artifacts (if you want a backup in the Actions tab)
    - name: Upload resume outputs
      uses: actions/upload-artifact@v3
      with:
        name: resume-files
        path: |
          *.pdf
          *.docx
          *.txt
          *.html
