name: Build and Commit Resume

on:
  push:
    paths:
      - "BilalShehzadResume.md"   # Only trigger on changes to BilalShehzadResume.md

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Cache APT package downloads
    - name: Cache APT packages
      uses: actions/cache@v3
      with:
        path: /var/cache/apt
        key: ${{ runner.os }}-apt-cache
        restore-keys: |
          ${{ runner.os }}-apt-cache

    # Install dependencies: pandoc, wkhtmltopdf, and make
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc wkhtmltopdf make

    # Build the resume in all formats
    - name: Build resume
      run: |
        make clean
        make all

    # Configure Git and commit the resume files
    - name: Configure Git and Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add *.pdf *.docx *.txt *.html
        git commit -m 'Auto-update resume formats [skip ci]' || echo 'No changes to commit'
        git push origin HEAD

    # Upload resume artifacts for easy download
    - name: Upload resume outputs
      uses: actions/upload-artifact@v3
      with:
        name: resume-files
        path: |
          *.pdf
          *.docx
          *.txt
          *.html
